apiVersion: v1
kind: Service
metadata:
  name: node-service-nodep
spec:
  selector:
    app: node-service-nodep
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30080