apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-node-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-node-app
  template:
    metadata:
      labels:
        app: sample-node-app
    spec:
      containers:
      - name: sample-node-app
        image: haiderali956/node-image:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
   